package poeCraftingSim.client.enums;

public enum OrbTypes {
	SCRAPS, WHETSTONE, TRANSMUTATIONORB, AUGMENTATIONORB, ALTERATIONORB, CHROMATICORB, JEWELERORB, CHANCEORB, ALCHEMYORB, REGALORB, 
	CHAOSORB, FUSINGORB, BLESSEDORB, SCOURINGORB, VAALORB, DIVINEORB, EXALTEDORB, ETERNALORB, MIRROROFKALANDRA
}